# Site settings
title: Yuki Nishijima's Blog
subtitle: ""
email: mail@yukinishijima.net
description: "Maintainer of kaminari, contributor of many open source projects including Ruby on Rails."
baseurl: ""
url: "http://www.yukinishijima.net"
twitter_username: "yuki24"
github_username:  "yuki24"

# Build settings
markdown: redcarpet
permalink: /:year/:month/:day/:title.html

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed
